./ttskokoro.py ../db/output/antichrist.md mp3/antichrist.mp3
./ttskokoro.py ../db/output/arcticfrost.md mp3/arcticfrost.mp3
./ttskokoro.py ../db/output/argentina.md mp3/argentina.mp3
./ttskokoro.py ../db/output/bolivia.md mp3/bolivia.mp3
./ttskokoro.py ../db/output/china.md mp3/china.mp3
./ttskokoro.py ../db/output/chinasea.md mp3/chinasea.mp3
./ttskokoro.py ../db/output/climate.md mp3/climate.mp3
./ttskokoro.py ../db/output/critmin.md mp3/critmin.mp3
./ttskokoro.py ../db/output/farage.md mp3/farage.mp3
./ttskokoro.py ../db/output/genz.md mp3/genz.mp3
./ttskokoro.py ../db/output/govshut.md mp3/govshut.mp3
./ttskokoro.py ../db/output/iran.md mp3/iran.mp3
./ttskokoro.py ../db/output/israel.md mp3/israel.mp3
./ttskokoro.py ../db/output/japan.md mp3/japan.mp3
./ttskokoro.py ../db/output/layoff.md mp3/layoff.mp3
./ttskokoro.py ../db/output/mantoxic.md mp3/mantoxic.mp3
./ttskokoro.py ../db/output/myanmar.md mp3/myanmar.mp3
./ttskokoro.py ../db/output/nigeriachrist.md mp3/nigeriachrist.mp3
./ttskokoro.py ../db/output/portland.md mp3/portland.mp3
./ttskokoro.py ../db/output/russia.md mp3/russia.mp3
./ttskokoro.py ../db/output/sanae.md mp3/sanae.mp3
./ttskokoro.py ../db/output/sudan.md mp3/sudan.mp3
./ttskokoro.py ../db/output/supreme.md mp3/supreme.mp3
./ttskokoro.py ../db/output/ukraine.md mp3/ukraine.mp3
