./ttskokoro.py ../db/output/afghanistan.md mp3/afghanistan.mp3
./ttskokoro.py ../db/output/antichrist.md mp3/antichrist.mp3
./ttskokoro.py ../db/output/antifa.md mp3/antifa.mp3
./ttskokoro.py ../db/output/arcticfrost.md mp3/arcticfrost.mp3
./ttskokoro.py ../db/output/argentina.md mp3/argentina.mp3
./ttskokoro.py ../db/output/bolivia.md mp3/bolivia.mp3
./ttskokoro.py ../db/output/chicago.md mp3/chicago.mp3
./ttskokoro.py ../db/output/china.md mp3/china.mp3
./ttskokoro.py ../db/output/climate.md mp3/climate.mp3
./ttskokoro.py ../db/output/dei.md mp3/dei.mp3
./ttskokoro.py ../db/output/france.md mp3/france.mp3
./ttskokoro.py ../db/output/gaza.md mp3/gaza.mp3
./ttskokoro.py ../db/output/genz.md mp3/genz.mp3
./ttskokoro.py ../db/output/govshut.md mp3/govshut.mp3
./ttskokoro.py ../db/output/hungary.md mp3/hungary.mp3
./ttskokoro.py ../db/output/iran.md mp3/iran.mp3
./ttskokoro.py ../db/output/israel.md mp3/israel.mp3
./ttskokoro.py ../db/output/japan.md mp3/japan.mp3
./ttskokoro.py ../db/output/jinping.md mp3/jinping.mp3
./ttskokoro.py ../db/output/layoff.md mp3/layoff.mp3
./ttskokoro.py ../db/output/madagascar.md mp3/madagascar.mp3
./ttskokoro.py ../db/output/mamdani.md mp3/mamdani.mp3
./ttskokoro.py ../db/output/mantoxic.md mp3/mantoxic.mp3
./ttskokoro.py ../db/output/morocco.md mp3/morocco.mp3
./ttskokoro.py ../db/output/myanmar.md mp3/myanmar.mp3
./ttskokoro.py ../db/output/nepal.md mp3/nepal.mp3
./ttskokoro.py ../db/output/nigeriachrist.md mp3/nigeriachrist.mp3
./ttskokoro.py ../db/output/nkorea.md mp3/nkorea.mp3
./ttskokoro.py ../db/output/pakistan.md mp3/pakistan.mp3
./ttskokoro.py ../db/output/poland.md mp3/poland.mp3
./ttskokoro.py ../db/output/putin.md mp3/putin.mp3
./ttskokoro.py ../db/output/russia.md mp3/russia.mp3
./ttskokoro.py ../db/output/sanae.md mp3/sanae.mp3
./ttskokoro.py ../db/output/skorea.md mp3/skorea.mp3
./ttskokoro.py ../db/output/sudan.md mp3/sudan.mp3
./ttskokoro.py ../db/output/supreme.md mp3/supreme.mp3
./ttskokoro.py ../db/output/syriachrist.md mp3/syriachrist.mp3
./ttskokoro.py ../db/output/uk.md mp3/uk.mp3
./ttskokoro.py ../db/output/ukraine.md mp3/ukraine.mp3
./ttskokoro.py ../db/output/venezuela.md mp3/venezuela.mp3
./ttskokoro.py ../db/output/votefraud.md mp3/votefraud.mp3
