startdate=$2
$1 "$startdate" venezuela "Venezuela" "Summarize US involvement in Venezuela. Analize actions and motivations."
$1 "$startdate" maduro "Maduro" "Summarize legal actions involving Maduro. Analize actions and motivations." "+legal,court,trial,arrest,indictment,charges,prosecution"
$1 "$startdate" cambodia "Cambodia" "Summarize current events in Cambodia. Analize actions and motivations." "+Cambodia"
$1 "$startdate" thailand "Thailand" "Summarize current events in Thailand. Analize actions and motivations." "+Thailand"
$1 "$startdate" jihad "Jihad,Islam,Muslim" "Summarize current events involving jihadist or jihad. Analize actions and motivations." "+Jihad,Jihadist"
$1 "$startdate" hk "Hong Kong" "Summarize current events in Hong Kong. Analize actions and motivations." "+Hong Kong"
$1 "$startdate" taiwan "Taiwan" "Summarize current events in Taiwan. Analize actions and motivations." "+Taiwan"
$1 "$startdate" israel "Israel" "Summarize current events in Israel. Analize actions and motivations." "+Israel"
$1 "$startdate" sudan "Sudan" "Summarize current events in Sudan. Analize actions and motivations." "+Sudan"
# $1 "$startdate" climate "Climate" "Summarize news about climate change and global warming. Analize actions and motivations." "+climate change"
$1 "$startdate" milei "Milei" "Summarize actions taken by Javier Milei. Analize actions and motivations."
$1 "$startdate" farage "Farage" "Summarize actions taken by Nigel Farage. Analize actions and motivations."
# $1 "$startdate" mantoxic "toxic masculinity" "Summarize all actions involving toxic masculinity. Analize actions and motivations." "toxic masculinity"
$1 "$startdate" iran "Iran" "Summarize news about Iran. Analize actions and motivations."
$1 "$startdate" arcticfrost "Arctic Frost" "Summarize news about Operation Arctic Frost. Analize actions and motivations." "+Arctic Frost"
$1 "$startdate" crossfire "Crossfire Hurricane" "Summarize news about Crossfire Hurricane. Analize actions and motivations." "+Crossfire Hurricane"
$1 "$startdate" comey "Comey" "Summarize news about James Comey. Analize actions and motivations." "+James Comey,trial,felony"
$1 "$startdate" argentina "Argentina" "Summarize news about Argentina. Analize actions and motivations."
$1 "$startdate" antichrist Christian "Summarize events about christians being killed or otherwise discriminated against. Summarize the locations. Analize actions and motivations." "+hate,violence,riot,kill,terror,attack"
$1 "$startdate" portland "Portland" "Summarize actions in Portland Oregon involving ICE, the Mayor and ANTIFA. Analize actions and motivations." "+ICE"
$1 "$startdate" cbdc "CBDC,Central Bank Digital Currencies" "Summarize crypto currency, CBDC central bank digital currency, or digital asset legislation and implementation plans. Analize actions and motivations." "+CBDC,Central Bank Digital Currency"
$1 "$startdate" votefraud "Voter ID" "Summarize stories having to do with voting fraud in the US, United States. List all details. Analize actions and motivations." "voter fraud"
# add election fraud
$1 "$startdate" digid "Digital ID,Face ID,Touch ID" "Summarize stories about digital ID. List places and specific actions. Analize actions and motivations." "+Digital ID,Face ID,Touch ID"
$1 "$startdate" supreme "US,U.S.,the United States" "Summarize current actions by the US Supreme Court. Analize actions and motivations." "+Supreme Court"
$1 "$startdate" chicago "Chicago" "Summarize actions in Chicago. Focus on the Mayor and Governor's actions. Analize actions and motivations." "+Chicago,Mayor,Governor"
$1 "$startdate" japan "Japan" "Summarize events in Japan. Analize actions and motivations."
$1 "$startdate" japanim "Japan" "Summarize immigration events in Japan. Analize actions and motivations." "+Japan,immagrant,immigration"
$1 "$startdate" bolivia "Bolivia" "Summarize events in Bolivia and actions by Rodrigo Paz. Analize actions and motivations." "Bolivia,Rodrigo Paz"
$1 "$startdate" critmin "China" "Summarize news about critical minerals and rare earths needed for high tech. Analize actions and motivations." "+rare earth,critical minerals"
$1 "$startdate" debank "debank" "Summarize all actions to debank or deny people bank accounts. Analize actions and motivations." "+debank,debanking"
$1 "$startdate" ukraine "Ukraine" "Summarize actions in the war in Ukraine. Analize actions and motivations." "+Ukraine war"
$1 "$startdate" chinasea "South China Sea" "Summarize actions in the South China Sea. Analize actions and motivations." "+South China Sea"
$1 "$startdate" earthquake "Earthquake" "Summarize any earthquakes, their location and damage. Summarize and analize actions taken by authorities."
$1 "$startdate" typhoon "Typhoon" "Summarize any typhoons, their location and damage. Summarize and analize actions taken by authorities."
$1 "$startdate" myanmar "Myanmar" "Summarize actions in Myanmar. Focus on any violent actions. Analize actions and motivations."
$1 "$startdate" nigeriachrist "Nigeria,Christian" "Summarize events about christians being killed in Nigeria. Analize actions and motivations." "+Nigeria,Christian"
$1 "$startdate" syriachrist "Syria,Christian" "Summarize events about christians being killed in Syria. Analize actions and motivations." "+Syria,Christian"
$1 "$startdate" genz "Gen Z,Gen Z 212" "Summarize news about Gen-Z protests. List locations and groups involved. Analize actions and motivations." "+Gen Z"
$1 "$startdate" sanae "Sanae Takaichi" "Summarize all actions by Sanae Takaichi." "+Sanae Takaichi"
# $1 "$startdate" sexwar "Chinese,Russian" "Summarize news about foreign agents using sexual warfare to gain secrets and engage in espionage." "+Sex warfare"
$1 "$startdate" layoff "layoffs" "Summarize news about corporations laying off workers. Analize actions and motivations." "layoffs"
$1 "$startdate" antifa "Antifa,ANTIFA" "Summarize actions by ANTIFA and against them. Analize actions and motivations." "+Antifa,ANTIFA"
# $1 "$startdate" govshut "US,U.S." "Summarize details about a US government shutdown. Analize actions and motivations." "+shutdown"
$1 "$startdate" safarmer "South Africa" "Summarize actions in South Africa taken against White farmers. Analize actions and motivations." "+farmer,boer,white,farm"
$1 "$startdate" russia "Russia" "Summarize news about Russia. Analize actions and motivations."
$1 "$startdate" china "China" "Summarize news about China. Analize actions and motivations."
$1 "$startdate" afghanistan "Afghanistan" "Summarize news about Afghanistan. Analize actions and motivations."
$1 "$startdate" france "France" "Summarize news about France. Analize actions and motivations."
$1 "$startdate" hungary "Hungary" "Summarize news about Hungary. Analize actions and motivations."
$1 "$startdate" poland "Poland" "Summarize news about Poland. Analize actions and motivations."
$1 "$startdate" uk "UK,United Kingdom" "Summarize news about The United Kingdom. Analize actions and motivations."
$1 "$startdate" pakistan "Pakistan" "Summarize news about Pakistan. Analize actions and motivations."
$1 "$startdate" skorea "South Korea" "Summarize news about South Korea. Analize actions and motivations."
$1 "$startdate" nkorea "North Korea" "Summarize news about North Korea. Analize actions and motivations."

$1 "$startdate" gaza "Gaza" "Summarize events in Gaza. Analize actions and motivations."
$1 "$startdate" nepal "Nepal" "Summarize current events in Nepal. Analize actions and motivations."
$1 "$startdate" madagascar "Madagascar" "Summarize current events in Madagascar. Analize actions and motivations."
$1 "$startdate" morocco "Morocco" "Summarize current events in Morocco. Analize actions and motivations."
$1 "$startdate" dei "DEI,Equity and Inclusion" "Summarize all actions about DEI, diversity, equity and inclusion. Analize actions and motivations." "+DEI"
$1 "$startdate" putin "Putin" "Summarize all actions by Putin. Analize actions and motivations." "+Putin"
$1 "$startdate" jinping "Xi,Jinping" "Summarize all actions by Xi Jinping. Analize actions and motivations." "+Xi Jinping"
$1 "$startdate" mamdani "Mamdani" "Summarize all actions by Zohran Mamdani. Analize actions and motivations." "+Zohran Mamdani"