./entitybatch.sh israel "Israel" "Summarize current events in Sudan. Analize actions and motivations."
./entitybatch.sh sudan "Sudan" "Summarize current events in Sudan. Analize actions and motivations."
./entitybatch.sh climate "Climate" "Summarize news about climate change and global warming. Analize actions and motivations." "climate change"
./entitybatch.sh milei "Milei" "Summarize actions taken by Javier Milei. Analize actions and motivations."
./entitybatch.sh farage "Farage" "Summarize actions taken by Nigel Farage. Analize actions and motivations."
./entitybatch.sh mantoxic "toxic masculinity" "Summarize all actions involving toxic masculinity. Analize actions and motivations." "toxic masculinity"
./entitybatch.sh iran "Iran" "Summarize news about Iran. Analize actions and motivations."
./entitybatch.sh arcticfrost "Arctic Frost" "Summarize news about Operation Arctic Frost. Analize actions and motivations." "+Arctic Frost"
./entitybatch.sh crossfire "Crossfire Hurricane" "Summarize news about Crossfire Hurricane. Analize actions and motivations." "+Crossfire Hurricane"
./entitybatch.sh comey "Comey" "Summarize news about James Comey. Analize actions and motivations." "+James Comey,trial,felony"
./entitybatch.sh argentina "Argentina" "Summarize news about Argentina. Analize actions and motivations."
./entitybatch.sh antichrist Christian "Summarize events about christians being killed or otherwise discriminated against. Summarize the locations. Analize actions and motivations."
./entitybatch.sh portland "Portland" "Summarize actions in Portland Oregon involving ICE, the Mayor and ANTIFA. Analize actions and motivations." "+ICE"
./entitybatch.sh cbdc "CBDC,Central Bank Digital Currencies" "Summarize crypto currency, CBDC central bank digital currency, or digital asset legislation and implementation plans. Analize actions and motivations." "+CBDC,Central Bank Digital Currency"
./entitybatch.sh votefraud "Voter ID" "Summarize stories having to do with voting fraud in the US, United States. List all details. Analize actions and motivations." "voter fraud"
./entitybatch.sh digid "Digital ID,Face ID,Touch ID" "Summarize stories about digital ID. List places and specific actions. Analize actions and motivations." "+Digital ID,Face ID,Touch ID"
./entitybatch.sh supreme "US,U.S.,the United States" "Summarize current actions by the US Supreme Court. Analize actions and motivations." "+Supreme Court"
./entitybatch.sh chicago "Chicago" "Summarize actions in Chicago. Focus on the Mayor and Governor's actions. Analize actions and motivations." "+Chicago,Mayor,Governor"
./entitybatch.sh japan "Japan" "Summarize events in Japan. Analize actions and motivations."
./entitybatch.sh japanim "Japan" "Summarize immigration events in Japan. Analize actions and motivations." "+Japan,immagrant,immigration"
./entitybatch.sh bolivia "Bolivia" "Summarize events in Bolivia and actions by Rodrigo Paz. Analize actions and motivations." "Bolivia,Rodrigo Paz"
./entitybatch.sh critmin "China" "Summarize news about critical minerals and rare earths needed for high tech. Analize actions and motivations." "+rare earth,critical minerals"
./entitybatch.sh debank "debank" "Summarize all actions to debank or deny people bank accounts. Analize actions and motivations." "+debank,debanking"
./entitybatch.sh ukraine "Ukraine" "Summarize actions in the war in Ukraine. Analize actions and motivations." "+Ukraine war"
./entitybatch.sh chinasea "South China Sea" "Summarize actions in the South China Sea. Analize actions and motivations." "+South China Sea"
./entitybatch.sh earthquake "Earthquake" "Summarize any earthquakes, their location and damage. Summarize and analize actions taken by authorities."
./entitybatch.sh typhoon "Typhoon" "Summarize any typhoons, their location and damage. Summarize and analize actions taken by authorities."
./entitybatch.sh myanmar "Myanmar" "Summarize actions in Myanmar. Focus on any violent actions. Analize actions and motivations."
./entitybatch.sh nigeriachrist "Nigeria,Christian" "Summarize events about christians being killed in Nigeria. Analize actions and motivations." "+Nigeria,Christian"
./entitybatch.sh syriachrist "Syria,Christian" "Summarize events about christians being killed in Syria. Analize actions and motivations." "+Syria,Christian"
./entitybatch.sh genz "Gen Z,Gen Z 212" "Summarize news about Gen-Z protests. List locations and groups involved. Analize actions and motivations." "+Gen Z"
./entitybatch.sh sanae "Sanae Takaichi" "Summarize all actions by Sanae Takaichi." "+Sanae Takaichi"
./entitybatch.sh sexwar "Chinese,Russian" "Summarize news about foreign agents using sexual warfare to gain secrets and engage in espionage." "+Sex warfare"
./entitybatch.sh layoff "layoffs" "Summarize news about corporations laying off workers. Analize actions and motivations." "layoffs"
./entitybatch.sh antifa "Antifa,ANTIFA" "Summarize actions by ANTIFA and against them. Analize actions and motivations." "+Antifa,ANTIFA"
./entitybatch.sh govshut "US,U.S." "Summarize details about a US government shutdown. Analize actions and motivations." "+shutdown"
./entitybatch.sh safarmer "South Africa" "Summarize actions in South Africa taken against White farmers. Analize actions and motivations." "+farmer,boer,white,farm"
./entitybatch.sh russia "Russia" "Summarize news about Russia. Analize actions and motivations."
./entitybatch.sh china "China" "Summarize news about China. Analize actions and motivations."
./entitybatch.sh afghanistan "Afghanistan" "Summarize news about Afghanistan. Analize actions and motivations."
./entitybatch.sh france "France" "Summarize news about France. Analize actions and motivations."
./entitybatch.sh hungary "Hungary" "Summarize news about Hungary. Analize actions and motivations."
./entitybatch.sh poland "Poland" "Summarize news about Poland. Analize actions and motivations."
./entitybatch.sh uk "UK,United Kingdom" "Summarize news about The United Kingdom. Analize actions and motivations."
./entitybatch.sh pakistan "Pakistan" "Summarize news about Pakistan. Analize actions and motivations."
./entitybatch.sh skorea "South Korea" "Summarize news about South Korea. Analize actions and motivations."
./entitybatch.sh nkorea "North Korea" "Summarize news about South Korea. Analize actions and motivations."
./entitybatch.sh venezuela "Venezuela" "Summarize US involvement in Venezuela. Analize actions and motivations."
./entitybatch.sh gaza "Gaza" "Summarize events in Gaza. Analize actions and motivations."
./entitybatch.sh nepal "Nepal" "Summarize current events in Nepal. Analize actions and motivations."
./entitybatch.sh madagascar "Madagascar" "Summarize current events in Madagascar. Analize actions and motivations."
./entitybatch.sh morocco "Morocco" "Summarize current events in Morocco. Analize actions and motivations."
./entitybatch.sh dei "DEI,Equity and Inclusion" "Summarize all actions about DEI, diversity, equity and inclusion. Analize actions and motivations." "+DEI"
./entitybatch.sh putin "Putin" "Summarize all actions by Putin. Analize actions and motivations." "+Putin"
./entitybatch.sh jinping "Xi,Jinping" "Summarize all actions by Xi Jinping. Analize actions and motivations." "+Xi Jinping"
./entitybatch.sh mamdani "Mamdani" "Summarize all actions by Zohran Mamdani. Analize actions and motivations." "+Zohran Mamdani"