startdate="-1"
./mkvec.sh "$startdate" israel "Israel" "Summarize current events in Israel. Analize actions and motivations." "+Israel"
./mkvec.sh "$startdate" sudan "Sudan" "Summarize current events in Sudan. Analize actions and motivations."
./mkvec.sh "$startdate" climate "Climate" "Summarize news about climate change and global warming. Analize actions and motivations." "climate change"
./mkvec.sh "$startdate" milei "Milei" "Summarize actions taken by Javier Milei. Analize actions and motivations."
./mkvec.sh "$startdate" farage "Farage" "Summarize actions taken by Nigel Farage. Analize actions and motivations."
./mkvec.sh "$startdate" mantoxic "toxic masculinity" "Summarize all actions involving toxic masculinity. Analize actions and motivations." "toxic masculinity"
./mkvec.sh "$startdate" iran "Iran" "Summarize news about Iran. Analize actions and motivations."
./mkvec.sh "$startdate" arcticfrost "Arctic Frost" "Summarize news about Operation Arctic Frost. Analize actions and motivations." "+Arctic Frost"
./mkvec.sh "$startdate" crossfire "Crossfire Hurricane" "Summarize news about Crossfire Hurricane. Analize actions and motivations." "+Crossfire Hurricane"
./mkvec.sh "$startdate" comey "Comey" "Summarize news about James Comey. Analize actions and motivations." "+James Comey,trial,felony"
./mkvec.sh "$startdate" argentina "Argentina" "Summarize news about Argentina. Analize actions and motivations."
./mkvec.sh "$startdate" antichrist Christian "Summarize events about christians being killed or otherwise discriminated against. Summarize the locations. Analize actions and motivations."
./mkvec.sh "$startdate" portland "Portland" "Summarize actions in Portland Oregon involving ICE, the Mayor and ANTIFA. Analize actions and motivations." "+ICE"
./mkvec.sh "$startdate" cbdc "CBDC,Central Bank Digital Currencies" "Summarize crypto currency, CBDC central bank digital currency, or digital asset legislation and implementation plans. Analize actions and motivations." "+CBDC,Central Bank Digital Currency"
./mkvec.sh "$startdate" votefraud "Voter ID" "Summarize stories having to do with voting fraud in the US, United States. List all details. Analize actions and motivations." "voter fraud"
./mkvec.sh "$startdate" digid "Digital ID,Face ID,Touch ID" "Summarize stories about digital ID. List places and specific actions. Analize actions and motivations." "+Digital ID,Face ID,Touch ID"
./mkvec.sh "$startdate" supreme "US,U.S.,the United States" "Summarize current actions by the US Supreme Court. Analize actions and motivations." "+Supreme Court"
./mkvec.sh "$startdate" chicago "Chicago" "Summarize actions in Chicago. Focus on the Mayor and Governor's actions. Analize actions and motivations." "+Chicago,Mayor,Governor"
./mkvec.sh "$startdate" japan "Japan" "Summarize events in Japan. Analize actions and motivations."
./mkvec.sh "$startdate" japanim "Japan" "Summarize immigration events in Japan. Analize actions and motivations." "+Japan,immagrant,immigration"
./mkvec.sh "$startdate" bolivia "Bolivia" "Summarize events in Bolivia and actions by Rodrigo Paz. Analize actions and motivations." "Bolivia,Rodrigo Paz"
./mkvec.sh "$startdate" critmin "China" "Summarize news about critical minerals and rare earths needed for high tech. Analize actions and motivations." "+rare earth,critical minerals"
./mkvec.sh "$startdate" debank "debank" "Summarize all actions to debank or deny people bank accounts. Analize actions and motivations." "+debank,debanking"
./mkvec.sh "$startdate" ukraine "Ukraine" "Summarize actions in the war in Ukraine. Analize actions and motivations." "+Ukraine war"
./mkvec.sh "$startdate" chinasea "South China Sea" "Summarize actions in the South China Sea. Analize actions and motivations." "+South China Sea"
./mkvec.sh "$startdate" earthquake "Earthquake" "Summarize any earthquakes, their location and damage. Summarize and analize actions taken by authorities."
./mkvec.sh "$startdate" typhoon "Typhoon" "Summarize any typhoons, their location and damage. Summarize and analize actions taken by authorities."
./mkvec.sh "$startdate" myanmar "Myanmar" "Summarize actions in Myanmar. Focus on any violent actions. Analize actions and motivations."
./mkvec.sh "$startdate" nigeriachrist "Nigeria,Christian" "Summarize events about christians being killed in Nigeria. Analize actions and motivations." "+Nigeria,Christian"
./mkvec.sh "$startdate" syriachrist "Syria,Christian" "Summarize events about christians being killed in Syria. Analize actions and motivations." "+Syria,Christian"
./mkvec.sh "$startdate" genz "Gen Z,Gen Z 212" "Summarize news about Gen-Z protests. List locations and groups involved. Analize actions and motivations." "+Gen Z"
./mkvec.sh "$startdate" sanae "Sanae Takaichi" "Summarize all actions by Sanae Takaichi." "+Sanae Takaichi"
./mkvec.sh "$startdate" sexwar "Chinese,Russian" "Summarize news about foreign agents using sexual warfare to gain secrets and engage in espionage." "+Sex warfare"
./mkvec.sh "$startdate" layoff "layoffs" "Summarize news about corporations laying off workers. Analize actions and motivations." "layoffs"
./mkvec.sh "$startdate" antifa "Antifa,ANTIFA" "Summarize actions by ANTIFA and against them. Analize actions and motivations." "+Antifa,ANTIFA"
./mkvec.sh "$startdate" govshut "US,U.S." "Summarize details about a US government shutdown. Analize actions and motivations." "+shutdown"
./mkvec.sh "$startdate" safarmer "South Africa" "Summarize actions in South Africa taken against White farmers. Analize actions and motivations." "+farmer,boer,white,farm"
./mkvec.sh "$startdate" russia "Russia" "Summarize news about Russia. Analize actions and motivations."
./mkvec.sh "$startdate" china "China" "Summarize news about China. Analize actions and motivations."
./mkvec.sh "$startdate" afghanistan "Afghanistan" "Summarize news about Afghanistan. Analize actions and motivations."
./mkvec.sh "$startdate" france "France" "Summarize news about France. Analize actions and motivations."
./mkvec.sh "$startdate" hungary "Hungary" "Summarize news about Hungary. Analize actions and motivations."
./mkvec.sh "$startdate" poland "Poland" "Summarize news about Poland. Analize actions and motivations."
./mkvec.sh "$startdate" uk "UK,United Kingdom" "Summarize news about The United Kingdom. Analize actions and motivations."
./mkvec.sh "$startdate" pakistan "Pakistan" "Summarize news about Pakistan. Analize actions and motivations."
./mkvec.sh "$startdate" skorea "South Korea" "Summarize news about South Korea. Analize actions and motivations."
./mkvec.sh "$startdate" nkorea "North Korea" "Summarize news about South Korea. Analize actions and motivations."
./mkvec.sh "$startdate" venezuela "Venezuela" "Summarize US involvement in Venezuela. Analize actions and motivations."
./mkvec.sh "$startdate" gaza "Gaza" "Summarize events in Gaza. Analize actions and motivations."
./mkvec.sh "$startdate" nepal "Nepal" "Summarize current events in Nepal. Analize actions and motivations."
./mkvec.sh "$startdate" madagascar "Madagascar" "Summarize current events in Madagascar. Analize actions and motivations."
./mkvec.sh "$startdate" morocco "Morocco" "Summarize current events in Morocco. Analize actions and motivations."
./mkvec.sh "$startdate" dei "DEI,Equity and Inclusion" "Summarize all actions about DEI, diversity, equity and inclusion. Analize actions and motivations." "+DEI"
./mkvec.sh "$startdate" putin "Putin" "Summarize all actions by Putin. Analize actions and motivations." "+Putin"
./mkvec.sh "$startdate" jinping "Xi,Jinping" "Summarize all actions by Xi Jinping. Analize actions and motivations." "+Xi Jinping"
./mkvec.sh "$startdate" mamdani "Mamdani" "Summarize all actions by Zohran Mamdani. Analize actions and motivations." "+Zohran Mamdani"